- name: Despliegue de contenedores en la VM
  hosts: all
  become: yes
  tasks:

    - name: Instalar Podman
      apt:
        name: podman
        state: present
        update_cache: true

    - name: Login en Azure Container Registry (usando Azure CLI)
      ansible.builtin.shell: az acr login --name containerregistrylfd
      register: acr_login
      changed_when: false

    - name: Descargar imagen NGINX desde ACR
      ansible.builtin.shell: podman pull containerregistrylfd.azurecr.io/nginx:latest
      register: pull_nginx
      changed_when: false

    - name: Verificar si NGINX está corriendo
      ansible.builtin.shell: "podman ps --filter name=nginx --format '{{.Names}}'"
      register: nginx_running
      changed_when: false

    - name: Lanzar contenedor NGINX si no existe
      ansible.builtin.shell: podman run -d --name nginx -p 8080:80 containerregistrylfd.azurecr.io/nginx:latest
      when: nginx_running.stdout == ""

    - name: Descargar imagen perros y gatos
      ansible.builtin.shell: podman pull thvs86/cats-v-dogs-vote
      register: pull_dogs_cats
      changed_when: false

    - name: Verificar si perros y gatos está corriendo
      ansible.builtin.shell: "podman ps --filter name=dogs-vs-cats --format '{{.Names}}'"
      register: dogs_cats_running
      changed_when: false

    - name: Lanzar app perros y gatos si no existe
      ansible.builtin.shell: podman run -d --name dogs-vs-cats -p 5000:5000 thvs86/cats-v-dogs-vote
      when: dogs_cats_running.stdout == ""